### ISSUE TITLE
"previous" option or record of your votes

### ISSUE THREAD

**Issue by RwwL** [johnotander/random-a11y#15]
This is a really cool project. I spent a minute voting on combinations and then saw one I really liked, to the point that I wanted to jot it down to use in a design, but the thought hit me just as I hit the voting button, and it was gone. That made me wonder about trying to author a pull request that either provided a "previous" button, or kept localStorage list of combinations you've voted on, or some other means of getting back to combinations you've already seen. Think there'd be any value in that? If so, lmk if you have a preferred approach.

**Comment by johnotander** [comment]
Yes! I'd intended on adding a feature where we stored previously voted combos in localStorage and having a history page to view past up/down votes. If you'd like to open up a PR (even a WIP) with that functionality, that'd be great!

**Comment by RwwL** [comment]
OK, cool. Got cloned, packages installed, but hit these errors on `npm start`; seen 'em before? Not sure if it matters but any specific node version I should be on for local development?

```ERROR in ./src/containers/Explore.js
Module not found: Error: Cannot resolve module 'is-present' in /Users/[path]/random-a11y/src/containers
 @ ./src/containers/Explore.js 25:17-38

ERROR in ./src/containers/App.js
Module not found: Error: Cannot resolve module 'is-present' in /Users/[path]/random-a11y/src/containers
 @ ./src/containers/App.js 33:17-38

ERROR in ./src/containers/App.js
Module not found: Error: Cannot resolve module 'is-blank' in /Users/[path]/random-a11y/src/containers
 @ ./src/containers/App.js 37:15-34

ERROR in ./src/containers/App.js
Module not found: Error: Cannot resolve module 'get-contrast' in /Users/[path]/random-a11y/src/containers
 @ ./src/containers/App.js 41:19-42```

**Comment by johnotander** [comment]
Hm, looks like I forgot to add those packages to the `package.json`. My bad 😊 . I've now added them, so you should be able to pull in the latest changes and rerun npm install. Let me know if that doesn't work for you. Node 5+ should work great.

**Comment by RwwL** [comment]
Does `babel-register` need to be in the `package.json` too? I get a `Cannot find module 'babel-register'` crash when I try to run `npm t` for the tests.

**Comment by RwwL** [comment]
I added it and it got the tests passing, so I'm gonna go ahead and assume yes and check that in on my fork :)
