### ISSUE TITLE
Animate color transitions

### ISSUE THREAD

**Issue by johnotander** [johnotander/random-a11y#24]
> It would be great to animate the color transitions between states as people vote.

via johnotander/immutable-css#39

**Comment by lachlanjc** [comment]
Not sure if I’ll get to this or not, but a great package for React animations is [velocity-react](https://github.com/twitter-fabric/velocity-react) :+1:

**Comment by lachlanjc** [comment]
Working on this now 👍

**Comment by lachlanjc** [comment]
@johnotander Having some trouble animating in the direction of the vote (up if you voted up, etc) — though I fixed the bug overwriting `currentVote`, the animator can’t handle switching directions at the same time as its animating. I think I’ll just go for a fade.

**Comment by lachlanjc** [comment]
Update: I’m going to let someone else work on this. I’ve spent a bunch of time thrashing around trying to figure it out, and I think someone else may be able to do it very quickly, so…😊

**Comment by johnotander** [comment]
No worries : ) Thanks for looking into it!

**Comment by samjbmason** [comment]
@johnotander  Picking this up this eve, just to clarify the expected result, when someone votes or clicks `Next`, it will transition the colours rather than just snap to them?

**Comment by lachlanjc** [comment]
@samjbmason Yep. Ideally it would slide up/down depending on the vote type as well, but it wouldn't have to.

**Comment by samjbmason** [comment]
Oh i see so the colour block would actually move up or down depending on the action?

**Comment by johnotander** [comment]
Great, thanks @samjbmason! 👯 

Another option would be to fade to white/black and then to the new colors to "reset" before seeing the new colors. But, ultimately the first step could be any transition to ensure the color change is less abrupt.

**Comment by johnotander** [comment]
Closed by #41
