### ISSUE TITLE
Nuke the success flash

### ISSUE THREAD

**Issue by johnotander** [johnotander/random-a11y#43]

**Comment by lachlanjc** [comment]
This would be pretty easy with a CSS animation :+1:

**Comment by johnotander** [comment]
Actually, after a quick discussion with @mrmrs we think it'd be best to no longer show it since the fact that the colors transitioned already indicates success.

**Comment by lachlanjc** [comment]
Sounds good.

**Comment by samjbmason** [comment]
Implemented in #46
