### ISSUE TITLE
No link back to the voting page

### ISSUE THREAD

**Issue by jamiestrachan** [johnotander/random-a11y#50]
As soon as you use any of the "Useful" links in the footer, there is no link back to the voting page.

**Comment by jamiestrachan** [comment]
My really simple suggestion here is to just turn the site title into a home link. I'm not sure it completely solves the problem but I think it would help.

**Comment by johnotander** [comment]
Ah, yep. This is a problem. Agree, we can start with linking the header back to the root page. Perhaps we could also add another call to action to vote at the very bottom of the page as well?

Thanks for creating this issue! 👯
