### ISSUE TITLE
Pull colors from query params

### ISSUE THREAD

**Issue by lachlanjc** [johnotander/random-a11y#55]
We need to be able to show a combination from query params in the URL. The exact names haven’t been decided, but @johnotander [suggested](https://github.com/johnotander/random-a11y/issues/25#issuecomment-234741483) that since you can already add `?hex=fff` maybe something like `?hex=fff&compare=444`.

**Comment by samjbmason** [comment]
A useful addition to this would be to add the colour hex codes as url params on every combination as it would be easier to share the url of a specific colour combo with people

**Comment by johnotander** [comment]
Yeah, absolutely. Would be great to make the urls shareable.

**Comment by lachlanjc** [comment]
and savable, if you want to manually collect a list of your favorites combos :+1:

**Comment by lachlanjc** [comment]
You did this, so I think we can close this @johnotander?
