### ISSUE TITLE
Add downloadable CSS for the color combination

### ISSUE THREAD

**Issue by johnotander** [johnotander/random-a11y#8]

**Comment by lachlanjc** [comment]
I’m working on this :+1:

**Comment by lachlanjc** [comment]
@johnotander Do you like this? Would it be better to have the CSS for each right underneath the color codes?

<img width="1440" alt="screen shot 2016-07-21 at 2 46 43 pm" src="https://cloud.githubusercontent.com/assets/5074763/17034761/15b90084-4f52-11e6-8e5a-f62c949a5de6.png">

**Comment by johnotander** [comment]
That's great! I like it being located under the voting buttons since the primary purpose is voting and the CSS is an added "nicety". 👯 👯

**Comment by lachlanjc** [comment]
Ok, PR ready! #37
